TELEBOT_TOKEN = '679219903:AAG413X11Psjp1YbjoYJsNCA4nj7Jbr2fKQ'
MAIN_URL = f'https://api.telegram.org/bot{TELEBOT_TOKEN}'
STICKER_ID = 'CAADAgADggIAAlwohgj91172rg2WVAI'
photo1 = '../staticfiles/Photos/welcome_img.jpg'
photo2 = '../staticfiles/Photos/bars_info.jpg'
photo3 = '../staticfiles/Photos/connect.jpg'
doc1 = '../staticfiles/Docs/agreement.docx'